export const recommendationsTestData = {
    meta: {
        status: 200,
        code: "HTTP_200",
    },
    data: {
        metadata: {
            title: "おすすめの動画 - ニコニコ動画",
            linkTags: [],
            metaTags: [],
            jsonLds: [],
        },
        googleTagManager: {
            user: {
                login_status: "not_login",
            },
        },
        response: {
            $getRecommend: {
                meta: {
                    status: 200,
                    code: "HTTP_200",
                },
                data: {
                    recipe: {
                        id: "recommendations_recipe",
                        meta: null,
                    },
                    recommendId: "test-recommend-id",
                    items: [
                        {
                            id: "sm10000001",
                            contentType: "video",
                            recommendType: "tag",
                            content: {
                                type: "video",
                                id: "sm10000001",
                                contentType: "long",
                                title: "テスト用動画 その1",
                                registeredAt: "2024-01-01T00:00:00+09:00",
                                count: { views: 1234, comments: 56, likes: 78, mylists: 9 },
                                thumbnail: {
                                    listingUrl: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    listingUrlHttps: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    nWidthHHeight: "1280x720",
                                    shortUrl: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    shortUrlHttps: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    fullScale: null,
                                    fullScaleHttps: null,
                                    viewer: null,
                                    viewerHttps: null,
                                },
                                duration: 300,
                                shortDescription: "テスト用の説明文1",
                                latestCommentSummary: "",
                                isChannelVideo: false,
                                isPaymentRequired: false,
                                playbackPosition: null,
                                owner: {
                                    id: "1000",
                                    name: "テストユーザー1",
                                    iconUrl: "https://resource.video.nimg.jp/web/images/no-user-icon.png",
                                    ownerType: "user",
                                    visibility: "public",
                                },
                                requireSensitiveMasking: false,
                                videoLive: null,
                                isMuted: false,
                            },
                            reason: {
                                tag: "テストタグ1",
                            },
                        },
                        {
                            id: "sm10000002",
                            contentType: "video",
                            recommendType: "tag",
                            content: {
                                type: "video",
                                id: "sm10000002",
                                contentType: "long",
                                title: "テスト用動画 その2",
                                registeredAt: "2024-01-02T00:00:00+09:00",
                                count: { views: 2345, comments: 67, likes: 89, mylists: 10 },
                                thumbnail: {
                                    listingUrl: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    listingUrlHttps: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    nWidthHHeight: "1280x720",
                                    shortUrl: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    shortUrlHttps: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    fullScale: null,
                                    fullScaleHttps: null,
                                    viewer: null,
                                    viewerHttps: null,
                                },
                                duration: 600,
                                shortDescription: "テスト用の説明文2",
                                latestCommentSummary: "",
                                isChannelVideo: false,
                                isPaymentRequired: false,
                                playbackPosition: null,
                                owner: {
                                    id: "1001",
                                    name: "テストユーザー2",
                                    iconUrl: "https://resource.video.nimg.jp/web/images/no-user-icon.png",
                                    ownerType: "user",
                                    visibility: "public",
                                },
                                requireSensitiveMasking: false,
                                videoLive: null,
                                isMuted: false,
                            },
                            reason: {
                                tag: "テストタグ2",
                            },
                        },
                        {
                            id: "sm10000003",
                            contentType: "video",
                            recommendType: "tag",
                            content: {
                                type: "video",
                                id: "sm10000003",
                                contentType: "long",
                                title: "テスト用動画 その3",
                                registeredAt: "2024-01-03T00:00:00+09:00",
                                count: { views: 3456, comments: 78, likes: 90, mylists: 11 },
                                thumbnail: {
                                    listingUrl: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    listingUrlHttps: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    nWidthHHeight: "1280x720",
                                    shortUrl: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    shortUrlHttps: "https://resource.video.nimg.jp/web/images/no-thumbnail.png",
                                    fullScale: null,
                                    fullScaleHttps: null,
                                    viewer: null,
                                    viewerHttps: null,
                                },
                                duration: 900,
                                shortDescription: "テスト用の説明文3",
                                latestCommentSummary: "",
                                isChannelVideo: false,
                                isPaymentRequired: false,
                                playbackPosition: null,
                                owner: {
                                    id: "1002",
                                    name: "テストユーザー3",
                                    iconUrl: "https://resource.video.nimg.jp/web/images/no-user-icon.png",
                                    ownerType: "user",
                                    visibility: "public",
                                },
                                requireSensitiveMasking: false,
                                videoLive: null,
                                isMuted: false,
                            },
                            reason: {
                                tag: "テストタグ1",
                            },
                        },
                    ],
                },
            },
            page: {
                playlist: "test-playlist",
            },
        },
    },
}
