name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.5

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: TypeScript Check
        run: pnpm compile

      - name: Zip extensions
        run: |
          pnpm zip
          pnpm zip:firefox

      - name: Upload a Build Artifact ( Chrome )
        uses: actions/upload-artifact@v4.6.1
        with:
          # Artifact name
          name: chrome-zip
          # A file, directory or wildcard pattern that describes what to upload
          path: .output/*-chrome.zip
          # The desired behavior if no files are found using the provided path.
          # Available Options:
          # warn: Output a warning but do not fail the action
          # error: Fail the action with an error message
          # ignore: Do not output any warnings or errors, the action does not fail
          if-no-files-found: error

      - name: Upload a Build Artifact ( Firefox )
        uses: actions/upload-artifact@v4.6.1
        with:
          # Artifact name
          name: firefox-zip
          # A file, directory or wildcard pattern that describes what to upload
          path: .output/*-firefox.zip
          # The desired behavior if no files are found using the provided path.
          # Available Options:
          # warn: Output a warning but do not fail the action
          # error: Fail the action with an error message
          # ignore: Do not output any warnings or errors, the action does not fail
          if-no-files-found: error
          

      
